vrrp_script check_nginx {
    script "/etc/keepalived/check_nginx.sh"
    interval 3
    weight 70
}

vrrp_instance VI_1 {
        state MASTER
        interface ens33
        virtual_router_id 15
        priority 250
        advert_int 1
        
        virtual_ipaddress {
              192.168.232.215/24
	    }

        track_script {
	      check_nginx

            }
}
