track_file track_check_priority {
    file "/etc/keepalived/check_priority"
}


vrrp_instance VI_1 {
    state MASTER
    interface ens33
    virtual_router_id 215
    priority 150
    advert_int 1

    virtual_ipaddress {
        192.168.232.215/24
    }

    track_file {
        track_check_priority
    }
}
